"""Initial core schema for PostgreSQL persistence

Mirrors agent_mcp/db/schema.py's SQLite tables for the core relational data
(agents, tasks, messages, oauth bindings, ...). RAG tables (rag_chunks,
rag_meta, rag_embeddings) are intentionally NOT included here: RAG content
is fully regenerated by the indexer from source material and stays on a
local SQLite file even when the core data is on PostgreSQL (see
db/connection.py's get_rag_db_connection()).

JSON-shaped columns (capabilities, notes, details, value, metadata, ...) and
timestamp columns are kept as TEXT rather than JSONB/TIMESTAMPTZ, matching
exactly how the existing SQLite schema stores them (json.dumps()/isoformat()
strings). The application code throughout the codebase already treats these
as opaque strings (`json.loads(row["capabilities"])`, lexicographic ISO8601
timestamp comparisons); switching column types would require touching
every one of those call sites for no functional benefit here.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-27

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "agents",
        sa.Column("token", sa.Text, primary_key=True),
        sa.Column("agent_id", sa.Text, nullable=False, unique=True),
        sa.Column("capabilities", sa.Text),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("status", sa.Text, nullable=False),
        sa.Column("current_task", sa.Text),
        sa.Column("working_directory", sa.Text, nullable=False),
        sa.Column("color", sa.Text),
        sa.Column("terminated_at", sa.Text),
        sa.Column("updated_at", sa.Text),
    )

    op.create_table(
        "oauth_agent_bindings",
        sa.Column("issuer", sa.Text, nullable=False),
        sa.Column("subject", sa.Text, nullable=False),
        sa.Column("client_id", sa.Text, nullable=False),
        sa.Column(
            "agent_id",
            sa.Text,
            sa.ForeignKey("agents.agent_id"),
            nullable=False,
        ),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("updated_at", sa.Text, nullable=False),
        sa.PrimaryKeyConstraint("issuer", "subject", "client_id"),
    )
    op.create_index(
        "idx_oauth_agent_bindings_agent_id",
        "oauth_agent_bindings",
        ["agent_id"],
    )

    op.create_table(
        "tasks",
        sa.Column("task_id", sa.Text, primary_key=True),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("assigned_to", sa.Text),
        sa.Column("created_by", sa.Text, nullable=False),
        sa.Column("status", sa.Text, nullable=False),
        sa.Column("priority", sa.Text, nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("updated_at", sa.Text, nullable=False),
        sa.Column("parent_task", sa.Text),
        sa.Column("child_tasks", sa.Text),
        sa.Column("depends_on_tasks", sa.Text),
        sa.Column("notes", sa.Text),
    )

    op.create_table(
        "agent_actions",
        sa.Column("action_id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("agent_id", sa.Text, nullable=False),
        sa.Column("action_type", sa.Text, nullable=False),
        sa.Column("task_id", sa.Text),
        sa.Column("timestamp", sa.Text, nullable=False),
        sa.Column("details", sa.Text),
    )
    op.create_index(
        "idx_agent_actions_agent_id_timestamp",
        "agent_actions",
        ["agent_id", sa.text("timestamp DESC")],
    )
    op.create_index(
        "idx_agent_actions_task_id_timestamp",
        "agent_actions",
        ["task_id", sa.text("timestamp DESC")],
    )

    op.create_table(
        "project_context",
        sa.Column("context_key", sa.Text, primary_key=True),
        sa.Column("value", sa.Text, nullable=False),
        sa.Column("last_updated", sa.Text, nullable=False),
        sa.Column("updated_by", sa.Text, nullable=False),
        sa.Column("description", sa.Text),
    )

    op.create_table(
        "file_metadata",
        sa.Column("filepath", sa.Text, primary_key=True),
        sa.Column("metadata", sa.Text, nullable=False),
        sa.Column("last_updated", sa.Text, nullable=False),
        sa.Column("updated_by", sa.Text, nullable=False),
        sa.Column("content_hash", sa.Text),
    )

    op.create_table(
        "agent_messages",
        sa.Column("message_id", sa.Text, primary_key=True),
        sa.Column("sender_id", sa.Text, nullable=False),
        sa.Column("recipient_id", sa.Text, nullable=False),
        sa.Column("message_content", sa.Text, nullable=False),
        sa.Column(
            "message_type", sa.Text, nullable=False, server_default="text"
        ),
        sa.Column("priority", sa.Text, nullable=False, server_default="normal"),
        sa.Column("timestamp", sa.Text, nullable=False),
        sa.Column(
            "delivered", sa.Boolean, nullable=False, server_default=sa.false()
        ),
        sa.Column("read", sa.Boolean, nullable=False, server_default=sa.false()),
    )
    op.create_index(
        "idx_agent_messages_recipient_timestamp",
        "agent_messages",
        ["recipient_id", sa.text("timestamp DESC")],
    )
    op.create_index(
        "idx_agent_messages_sender_timestamp",
        "agent_messages",
        ["sender_id", sa.text("timestamp DESC")],
    )
    op.create_index(
        "idx_agent_messages_unread",
        "agent_messages",
        ["recipient_id", "read", sa.text("timestamp DESC")],
    )

    op.create_table(
        "claude_code_sessions",
        sa.Column("session_id", sa.Text, primary_key=True),
        sa.Column("pid", sa.BigInteger, nullable=False),
        sa.Column("parent_pid", sa.BigInteger, nullable=False),
        sa.Column("first_detected", sa.Text, nullable=False),
        sa.Column("last_activity", sa.Text, nullable=False),
        sa.Column("working_directory", sa.Text),
        sa.Column("agent_id", sa.Text),
        sa.Column("status", sa.Text, server_default="detected"),
        sa.Column("git_commits", sa.Text),
        sa.Column("metadata", sa.Text),
    )
    op.create_index(
        "idx_claude_sessions_pid", "claude_code_sessions", ["pid", "parent_pid"]
    )
    op.create_index(
        "idx_claude_sessions_activity",
        "claude_code_sessions",
        [sa.text("last_activity DESC")],
    )
    op.create_index(
        "idx_claude_sessions_agent", "claude_code_sessions", ["agent_id"]
    )


def downgrade() -> None:
    op.drop_table("claude_code_sessions")
    op.drop_table("agent_messages")
    op.drop_table("file_metadata")
    op.drop_table("project_context")
    op.drop_table("agent_actions")
    op.drop_table("tasks")
    op.drop_table("oauth_agent_bindings")
    op.drop_table("agents")
